title: "ðŸ’™ 7OOP-Project â€” Hatsune Miku Edition"
description: "My Object-Oriented Programming Portfolio â€” Clean, Colorful & Miku-inspired."
theme: jekyll-theme-modernist

# Add social links (optional)
social_links:
  github: Aljohn013
  facebook: aljohnpaul.salalac.7

# Optional: Add logo
logo: https://github.com/user-attachments/assets/0b61e032-3fc6-4170-85e4-e1576add2a02

