title: "ðŸ’™ Hatsune Miku â€” OOP Portfolio"
description: "A futuristic, Miku-themed Object-Oriented Programming Portfolio by Aljohn."
theme: jekyll-theme-modernist

# Enable custom CSS
markdown: kramdown
include:
  - assets/css/custom.css

