title: "Aljohn's OOP Portfolio"
description: "A clean and modern programming portfolio featuring Java, C, and SQL projects."
theme: minima


markdown: kramdown
highlighter: rouge


sass:
style: compressed


author:
name: "Aljohn Paul Salalac"
avatar: "/assets/img/avatar.png"


social_links:
github: Aljohn013
facebook: aljohnpaul.salalac.7


plugins:
- jekyll-feed
- jekyll-seo-tag
