title: "Aljohnâ€™s OOP Portfolio"
description: "A programming portfolio featuring Java, C, and SQL projects."
theme: minima

author:
  name: "Aljohn Paul Salalac"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

sass:
  style: compressed

# IMPORTANT: Do NOT include CSS files here
# GitHub Pages auto-loads assets correctly
